//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemSearchTiger
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_504_SUPPASGN
    {
        public int LOGICALREF { get; set; }
        public Nullable<int> ITEMREF { get; set; }
        public Nullable<short> SUPPLYTYPE { get; set; }
        public Nullable<short> PRIORITY { get; set; }
        public Nullable<short> LINENR { get; set; }
        public Nullable<int> CLIENTREF { get; set; }
        public string TRADINGGRP { get; set; }
        public Nullable<short> CLCARDTYPE { get; set; }
        public Nullable<short> KKKCHECK { get; set; }
        public Nullable<double> LEADTIME { get; set; }
        public Nullable<double> MAXQUANTITY { get; set; }
        public Nullable<double> MINQUANTITY { get; set; }
        public Nullable<System.DateTime> BEGDATE { get; set; }
        public Nullable<short> SPECIALIZED { get; set; }
        public string ICUSTSUPCODE { get; set; }
        public string ICUSTSUPNAME { get; set; }
        public Nullable<double> QTYDEPLEADTIME { get; set; }
        public Nullable<int> PACKETREF { get; set; }
        public Nullable<double> PACKAGINGAMNT { get; set; }
        public Nullable<int> PACKAGINGUOMREF { get; set; }
        public Nullable<short> PACKETUSETYPE { get; set; }
        public Nullable<double> ORDPERC { get; set; }
        public Nullable<short> ORDFREQ { get; set; }
        public Nullable<int> VARIANTREF { get; set; }
        public string ICUSTSUPBARCODE { get; set; }
    }
}
