//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemSearchTiger
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_XT1001_504
    {
        public int LOGREF { get; set; }
        public Nullable<int> PARLOGREF { get; set; }
        public string AFiyat { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string SFiyat { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string E { get; set; }
        public string F { get; set; }
        public string G { get; set; }
        public string H { get; set; }
        public string I { get; set; }
        public string J { get; set; }
        public string Z { get; set; }
        public string B2BACK4 { get; set; }
        public string B2BACK5 { get; set; }
        public string B2BACK3 { get; set; }
        public string B2BACK1 { get; set; }
        public string B2BACK2 { get; set; }
        public string P { get; set; }
        public string Q { get; set; }
        public string R { get; set; }
        public string T { get; set; }
        public string S { get; set; }
        public string L { get; set; }
        public string K { get; set; }
        public string N { get; set; }
        public string O { get; set; }
        public string M { get; set; }
    }
}
