//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemSearchTiger
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TIGEREntities : DbContext
    {
        public TIGEREntities()
            : base("name=TIGEREntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LG_206_ITEMS> LG_206_ITEMS { get; set; }
        public virtual DbSet<LG_206_SUPPASGN> LG_206_SUPPASGN { get; set; }
        public virtual DbSet<LG_XT1001_206> LG_XT1001_206 { get; set; }
    }
}
